# Generated by Django 5.0.4 on 2024-04-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='имя пользователя')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='электронная почта')),
                ('password', models.CharField(max_length=20, unique=True, verbose_name='пароль')),
                ('telephone_number', models.CharField(blank=True, default='Не указано', max_length=20, unique=True, verbose_name='контактный номер')),
                ('my_activity', models.TextField(blank=True, default='Не указано', verbose_name='моя деятельность')),
                ('my_photo', models.ImageField(blank=True, default='Не добавлено', upload_to='user/', verbose_name='изображение')),
                ('date_register', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
        ),
    ]
