# Generated by Django 4.2.7 on 2023-12-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='имя пользователя')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='электронная почта')),
                ('password', models.CharField(max_length=20, unique=True, verbose_name='пароль')),
                ('date_register', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
        ),
    ]
