# Generated by Django 5.0.4 on 2024-04-12 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='регион')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='город')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.regions')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='склад')),
                ('square', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='площадь склада')),
                ('type_warehouse', models.CharField(max_length=24, verbose_name='тип склада')),
                ('type_of_sale', models.CharField(max_length=24, verbose_name='тип продажи')),
                ('image', models.ImageField(blank=True, upload_to='warehouse/', verbose_name='изображение')),
                ('description', models.TextField(blank=True, verbose_name='описание склада')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена')),
                ('address', models.CharField(max_length=200, verbose_name='адрес склада')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cities', verbose_name='город')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.regions', verbose_name='регион')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user', verbose_name='пользователь')),
            ],
        ),
    ]
