# Generated by Django 4.2.7 on 2024-01-15 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='город')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='регион')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='склад')),
                ('type_warehouse', models.CharField(max_length=24, verbose_name='тип склада')),
                ('type_of_sale', models.CharField(max_length=24, verbose_name='тип продажи')),
                ('image', models.ImageField(blank=True)),
                ('description', models.TextField(blank=True, verbose_name='описание склада')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена')),
                ('address', models.CharField(max_length=200, verbose_name='адрес склада')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cities')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.regions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.regions'),
        ),
    ]
