# Generated by Django 4.2.7 on 2024-01-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
    ]
