# Generated by Django 4.2.7 on 2024-01-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_warehouse_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='square',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='площадь склада'),
        ),
    ]
